language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: H4shZ4nf2FdujUaABiwANmVcKTh6FfKuY5kIxLkvq3NGDLBSav5r+SW+L4cJlrvnP88CaKuCCGBITrvc7Ynrr16jLhaFkxYvl5vKViINCP8wffVxZoV40ywsfi0v3mmVDoa3uaxvUZ9TS9j73lUUzkdt0oNLPWU72TzXJl5QO8wnqLsz1G4xINUvOezVByj2e2kv0vgXpneKIu0ar1eA7h6cgYsncaRZsSbEvj4HKg6mD003llQMtICZXcWKUNT2jWtzRc2YbTGdk85k/Gjiq5Xe+ojf96Mh1WbS8kHsN7nIT3cOTqTLk5nXiJNsjrcpAFz9p+PdAnqNbADqQnCuhLlylJRUoBdnqp3uKNkDB4Bqok4zowwaZpxheqiFcnzoBhlm80xT59G1tDq18iZOxAspE3TTOuFjb1mRhIcKB9LFypKAYqJ3Aot2P4EXcJxNBA0/w4SVZ9dX8uxw96aL0JbhOKIPe0KTM/go+IchZxhiK4d44rNmNQuPvgydya0OJ/PwdeAZe+Ja2BQVh4SIOyD3s88q/721P44nYMSxmWjo0+8S7Pn740MulINE3ftF5YdEI9syVF7TwFEWAYbg9H17pMIttnvb6rKlN4aEv5SJngI3Tj1xwHHioZXl27O3zf/pzyqBqbBiAp4W5ioFYRDDqBYakCkzQ7JH5ystpdI=
  app: peaceful-caverns-46117
  on:
    repo: ryandthorn/blog-api-v2
